version: '3.8'

services:
  db:
    build: .
    container_name: lr3_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    volumes:
      - ./:/docker-entrypoint-initdb.d
    restart: unless-stopped 