version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest  # Змінено на SQL Server 2022
    container_name: pr4_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd  # Пароль для адміністратора
    ports:
      - "1433:1433"  # Відкриваємо порт для доступу
    volumes:
      - ./pr4:/scripts  # Монтуючи вашу папку з SQL скриптами
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge
