version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest  
    container_name: pr5_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd  
    ports:
      - "1433:1433"  
    volumes:
      - ./pr5:/scripts  
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge
